version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      MONGO_DB_HOST: ${MONGO_DB_HOST}
      MONGO_DB_PORT: ${MONGO_DB_PORT}
      MONGO_DB_DATABASE: ${MONGO_DB_DATABASE}

  db:
    image: mongo:7.0.12
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongo-data:
